/**
 * taskIcons.js — list of supported custom task icons and their MDI paths.
 * Marker is the character inside the brackets: e.g., [?] → marker '?'
 */
import {
  mdiCircleHalfFull,
  mdiMinusCircle,
  mdiArrowRight,
  mdiCalendar,
  mdiHelpCircle,
  mdiAlertCircle,
  mdiStar,
  mdiFormatQuoteClose,
  mdiMapMarker,
  mdiBookmark,
  mdiInformation,
  mdiCurrencyUsd,
  mdiLightbulb,
  mdiThumbUp,
  mdiThumbDown,
  mdiFireCircle,
  mdiKey,
  mdiTrophy,
  mdiTrendingUp,
  mdiTrendingDown,
  mdiSourcePull,
  mdiSourceMerge,
} from '@mdi/js';

export const TASK_ICONS = [
  { marker: '/', label: 'incomplete', iconPath: mdiCircleHalfFull },
  { marker: '-', label: 'cancelled', iconPath: mdiMinusCircle },
  { marker: '>', label: 'forwarded', iconPath: mdiArrowRight },
  { marker: '<', label: 'scheduling', iconPath: mdiCalendar },
  { marker: '?', label: 'question', iconPath: mdiHelpCircle },
  { marker: '!', label: 'important', iconPath: mdiAlertCircle },
  { marker: '*', label: 'star', iconPath: mdiStar },
  { marker: '"', label: 'quote', iconPath: mdiFormatQuoteClose },
  { marker: 'l', label: 'location', iconPath: mdiMapMarker },
  { marker: 'b', label: 'bookmark', iconPath: mdiBookmark },
  { marker: 'i', label: 'information', iconPath: mdiInformation },
  { marker: 'S', label: 'savings', iconPath: mdiCurrencyUsd },
  { marker: 'I', label: 'idea', iconPath: mdiLightbulb },
  { marker: 'p', label: 'pros', iconPath: mdiThumbUp },
  { marker: 'c', label: 'cons', iconPath: mdiThumbDown },
  { marker: 'f', label: 'fire', iconPath: mdiFireCircle },
  { marker: 'k', label: 'key', iconPath: mdiKey },
  { marker: 'w', label: 'win', iconPath: mdiTrophy },
  { marker: 'u', label: 'up', iconPath: mdiTrendingUp },
  { marker: 'd', label: 'down', iconPath: mdiTrendingDown },
  { marker: 'D', label: 'draft pull request', iconPath: mdiSourcePull },
  { marker: 'P', label: 'open pull request', iconPath: mdiSourcePull },
  { marker: 'M', label: 'merged pull request', iconPath: mdiSourceMerge },
];